"""create listings table

Revision ID: b8b231420ed5
Revises: 
Create Date: 2026-04-21 16:42:47.153360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b231420ed5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=32), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('frame_size', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('seller_name', sa.String(length=120), nullable=False),
    sa.Column('seller_email', sa.String(length=254), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listings')
    # ### end Alembic commands ###
